[package]
name = "drop"
authors = ["jakeroggenbuck <jakeroggenbuck2@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
structopt = { version = "0.3", default-features = false }
